# Generated by Django 3.2.6 on 2021-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
